# Generated by Django 2.0 on 2020-03-01 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=300)),
                ('event_date', models.DateField()),
                ('booking_from', models.DateField()),
                ('booking_to', models.DateField()),
                ('booking_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('upload_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('is_photographer', models.BooleanField(default=False)),
                ('profile_views', models.IntegerField(default=0)),
                ('profile_picture', models.ImageField(blank=True, upload_to='images/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(blank=True, max_length=200)),
                ('instagram_id', models.CharField(blank=True, max_length=200)),
                ('pinterest_id', models.CharField(blank=True, max_length=200)),
                ('youtube_channel', models.CharField(blank=True, max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Tags'),
        ),
        migrations.AddField(
            model_name='images',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Profile'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='photographer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_id', to='photohireapp.Profile'),
        ),
        migrations.AddField(
            model_name='bookings',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='photohireapp.Profile'),
        ),
    ]
