# Generated by Django 3.0.3 on 2020-02-26 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photohireapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=5000)),
                ('likes', models.PositiveIntegerField()),
                ('upload_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['upload_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('bio', models.TextField()),
                ('is_photographer', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(max_length=200)),
                ('instagram_id', models.CharField(max_length=200)),
                ('pinterest_id', models.CharField(max_length=200)),
                ('youtube_channel', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_timestamp', models.DateTimeField(auto_now=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Images')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Person')),
            ],
            options={
                'ordering': ['liked_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='images',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Tags'),
        ),
        migrations.AddField(
            model_name='images',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Person'),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=300)),
                ('event_date', models.DateField()),
                ('booking_from', models.DateField()),
                ('booking_to', models.DateField()),
                ('booking_timestamp', models.DateTimeField(auto_now=True)),
                ('photographer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer_id', to='photohireapp.Person')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_id', to='photohireapp.Person')),
            ],
        ),
    ]
