# Generated by Django 3.0.3 on 2020-02-26 19:24

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('photohireapp', '0002_auto_20200227_0012'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Person',
        ),
    ]
