# Generated by Django 3.0.3 on 2020-03-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photohireapp', '0003_auto_20200301_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photohireapp.Profile')),
            ],
        ),
    ]
