# Generated by Django 3.0.3 on 2020-02-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohireapp', '0003_auto_20200227_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='url',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='social',
            name='pinterest_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='social',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='social',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
