# Generated by Django 3.0.3 on 2020-03-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohireapp', '0004_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='review',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
