# Generated by Django 3.0.3 on 2020-03-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohireapp', '0005_ratings_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='event_date',
        ),
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
