# Generated by Django 3.0.3 on 2020-03-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photohireapp', '0006_auto_20200321_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booking_timestamp',
        ),
    ]
