# Generated by Django 3.0.3 on 2020-03-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohireapp', '0007_remove_bookings_booking_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
