# Generated by Django 3.0.3 on 2020-03-21 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photohireapp', '0008_bookings_booking_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='id',
        ),
        migrations.AlterField(
            model_name='social',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='photohireapp.Profile'),
        ),
    ]
